version: '3'
services:
  frontend:
    image: node:latest
    container_name: frontend
    volumes:
      - .:/app
    working_dir: /app
    command: npm run serve
    ports:
      - "8080:8080"
    depends_on:
      - backend
  backend:
    image: node:latest
    container_name: backend
    volumes:
      - .:/app
    working_dir: /app
    command: npm run backend
    ports:
      - "3000:3000"
